### ISSUE TITLE
Help w/ NavBar

### ISSUE THREAD

**Issue by diabl0w** [shunf4/xposed-boox-tweaks-and-fixes#1]
Hey sorry this is really unrelated to this module, but I have been trying to debug a sort of related issue that maybe you have more knowledge than I do.

My desire is to have the navbar DISABLED, which it is by default on stock so no problems here. I am running stock rooted with magisk, but no modules. 

HOWEVER

In magisk's post-fs-data script folder (scripts that run early on boot right after /data is mounted), I have a script that sets selinux status to permissive (setenforce 0). Its strange, but just by doing this, it causes a navigation bar to show up upon boot (you can actually see the nav bar blink through the keyguard right after boot completes). It is really strange issue, as soon as I remove this setenforce 0, this no longer happens. 

Do you have any idea why setting selinux permissive would cause a navigation bar to show up? and how it might be prevented?

**Comment by shunf4** [comment]
It is very likely that Onyx's Android developers changed something for the convenience of themselves. They often do changes that confuse me a lot...

You may want to decompile `SystemUI.apk`, `framework-res.apk` or something else to confirm it

**Comment by diabl0w** [comment]
> It is very likely that Onyx's Android developers changed something for the convenience of themselves. They often do changes that confuse me a lot...
> 
> You may want to decompile `SystemUI.apk`, `framework-res.apk` or something else to confirm it

Yes, I agree on all your points. I already decompiled the apk's but cant find anything obvious. I'll keep looking, thanks!

**Comment by shunf4** [comment]
During a normal boot without touching SELinux, you can see the following message in logcat:

```
887   887 W libc    : Unable to set property "qemu.hw.mainkeys" to "0": error code: 0x18
```

Someone is always setting `qemu.hw.mainkeys` at boot, but when you have SELinux set to `enforcing`, the attempt is blocked by SELinux. So setting it to `permissive` allows that attempts and shows the navigation bar.

To find out who is setting this system property, I think [Riru](https://github.com/RikkaApps/Riru) is a good tool.

**Comment by diabl0w** [comment]
> During a normal boot without touching SELinux, you can see the following message in logcat:
> 
> ```
> 887   887 W libc    : Unable to set property "qemu.hw.mainkeys" to "0": error code: 0x18
> ```
> 
> Someone is always setting `qemu.hw.mainkeys` at boot, but when you have SELinux set to `enforcing`, the attempt is blocked by SELinux. So setting it to `permissive` allows that attempts and shows the navigation bar.
> 
> To find out who is setting this system property, I think [Riru](https://github.com/RikkaApps/Riru) is a good tool.

amazing! Thank you! I dont know how I missed that.... I'm not sure how I would use Riru to find out the process? I think maybe I could just find out which process is running via PID 887 (in your example) might work, but I'm not sure

**Comment by shunf4** [comment]
On my Max3 with ROM 2020-11-04_07_07_3.0_9aed398, it is caused by `/system/vendor/bin/init.qcom.sh`: https://github.com/LineageOS/android_device_oneplus_sdm845-common/blob/fac1372b4d18dc0f9185c20efc095c767048b358/rootdir/etc/init.qcom.sh#L360 (the file is identical to sdm845's).

A Magisk module overwriting it should fix the issue.

**Comment by diabl0w** [comment]
> On my Max3 with ROM 2020-11-04_07_07_3.0_9aed398, it is caused by `/system/vendor/bin/init.qcom.sh`: https://github.com/LineageOS/android_device_oneplus_sdm845-common/blob/fac1372b4d18dc0f9185c20efc095c767048b358/rootdir/etc/init.qcom.sh#L360 (the file is identical to sdm845's).
> 
> A Magisk module overwriting it should fix the issue.

You are 100% correct! This file was the culprit. Commenting out the proper line and replacing the file with magisk fixed the issue. Thanks again for your help, this was bugging me for months
